
declare namespace NodeJS {
  interface ProcessEnv {
		PLASMO_PUBLIC_FIREBASE_APP_ID?: string
		PLASMO_PUBLIC_FIREBASE_AUTH_DOMAIN?: string
		PLASMO_PUBLIC_FIREBASE_CLIENT_ID?: string
		PLASMO_PUBLIC_FIREBASE_MEASUREMENT_ID?: string
		PLASMO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID?: string
		PLASMO_PUBLIC_FIREBASE_PROJECT_ID?: string
		PLASMO_PUBLIC_FIREBASE_PUBLIC_API_KEY?: string
		PLASMO_PUBLIC_FIREBASE_STORAGE_BUCKET?: string
  }
}
